In [4]:
import numpy as np
# Create a NumPy array
orig_array = np.array([1, 2, 3, 4, 5])
print("Original Array:", orig_array)  # original array

# Reference assignment i.e.,ref array points to orig_array
ref_array = orig_array
ref_array[0] = 22  # This modifies the original as well

# Copy by value (creates a new independent array)
copy_array = orig_array.copy()
copy_array[1] = 99 # Does not affect the original array

# Display results
print("Original Array:", orig_array)  # original array
print("Reference Array:", ref_array)  # referenced array
print("Copied Array:", copy_array)  # copied array

Original Array: [1 2 3 4 5]
Original Array: [22  2  3  4  5]
Reference Array: [22  2  3  4  5]
Copied Array: [22 99  3  4  5]


In [13]:
import numpy as np
# Create a 5 by 5 random matrix
np.random.seed(77)  # For reproducibility
matrix = np.random.randint(1, 20, (4, 4))
print("Original Matrix:\n", matrix)

# Compute row-wise and column-wise sums
row_sums = matrix.sum(axis=1)
col_sums = matrix.sum(axis=0)

# Display results
print("Row-wise Sums:", row_sums)
print("Column-wise Sums:", col_sums)
# Normalize the matrix (Feature Scaling: Min-Max Scaling)
norm_matrix = (matrix - matrix.min()) / (matrix.max() - matrix.min())
print("Normalized Matrix:\n", np.round(norm_matrix, 2))
# extracting elements greater than or equal to 5
filt_matrix_elements = matrix[matrix >= 5]
print("Filtered Mtarix Elements (>=5):", filt_matrix_elements)



Original Matrix:
 [[12  6  1  8]
 [13  1  5  5]
 [16 15 16 11]
 [ 8  4  2 12]]
Row-wise Sums: [27 24 58 26]
Column-wise Sums: [49 26 24 36]
Normalized Matrix:
 [[0.73 0.33 0.   0.47]
 [0.8  0.   0.27 0.27]
 [1.   0.93 1.   0.67]
 [0.47 0.2  0.07 0.73]]
Filtered Mtarix Elements (>=5): [12  6  8 13  5  5 16 15 16 11  8 12]


In [18]:
""" Min Max Scaler Example"""
from sklearn.preprocessing import MinMaxScaler

data = np.array([[10], [20], [30], [40]])
print(f"orig data = {data}")
#This estimator scales and translates each feature 
# individually in the range [0,1]
scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(data)
print(f"scaled data = {scaled_data}")

orig data = [[10]
 [20]
 [30]
 [40]]
scaled data = [[0.        ]
 [0.33333333]
 [0.66666667]
 [1.        ]]


In [16]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)
print(f"orig data = {data}")
print(f"scaled data = {scaled_data}")

orig data = [[10]
 [20]
 [30]
 [40]]
scaled data = [[-1.34164079]
 [-0.4472136 ]
 [ 0.4472136 ]
 [ 1.34164079]]


In [17]:
from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()
scaled_data = scaler.fit_transform(data)
print(f"orig data = {data}")
print(f"scaled data = {scaled_data}")

orig data = [[10]
 [20]
 [30]
 [40]]
scaled data = [[-1.        ]
 [-0.33333333]
 [ 0.33333333]
 [ 1.        ]]
