In [11]:
import numpy as np

# Creating a 2D NumPy array that is 2 rows and 3 columns
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Original Array : = \n {arr}")
# Slicing the array
slice_arr = arr[:, 1:]  # Extracting last two columns
print("\nSliced Array:\n", slice_arr)
# Reshaping the array
reshaped_arr = arr.reshape(3, 2)  # Reshaping to 3 rows and 2 columns
print("\nReshaped Array:\n", reshaped_arr)
# Creating another array called arr2 for joining
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
print(f"Array2 = \n {arr2} and size is {arr2.shape}")
# Joining arrays along rows (axis=0)
joined_arr1 = np.concatenate((arr, arr2), axis=0)
print("\nJoined Array (axis=0):\n", joined_arr1)
# Joining arrays along columns (axis=1)
joined_arr2 = np.concatenate((arr, arr2), axis=1)
print("\nJoined Array (axis=1):\n", joined_arr2)


Original Array : = 
 [[1 2 3]
 [4 5 6]]

Sliced Array:
 [[2 3]
 [5 6]]

Reshaped Array:
 [[1 2]
 [3 4]
 [5 6]]
Array2 = 
 [[ 7  8  9]
 [10 11 12]] and size is (2, 3)

Joined Array (axis=0):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Joined Array (axis=1):
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [20]:
""" Sorting Numpy Arrays"""
import numpy as np
arr = np.array([9, 3, 2, 0, 1, 7, 8, 5, 4])
print(np.sort(arr))

binary_arr = np.array([True, False, False, True, False, False])
print(np.sort(binary_arr))

[0 1 2 3 4 5 7 8 9]
[False False False False  True  True]


In [21]:
""" In the following code iterate through all elements of the array
 and find all elements greater than a threshold value store them in a list
 and also note their index value and store that in another list
"""
import numpy as np
arr = np.array([11, 2, 13, 24, 5, 0 , 7, 17, 9, 8, 25, 7, 8, 9, 22, 17, 16, 3, 4 , 11])
# Create empty lists for values and their index values
list_arr = []
list_indx = []
indx = 0
# iterate through the array
for element in arr:
  # if the element is greate than or equals a threshold value
  if element >= 16:
    list_arr.append(element)
    list_indx.append(indx)
  indx = indx + 1
print(f"list_arr = {np.int64(list_arr)} and indices = {list_indx}")


list_arr = [24 17 25 22 17 16] and indices = [3, 7, 10, 14, 15, 16]
